// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { GraphNode } from './nua-serialization/graph-node.js';
export { Hotspot } from './nua-serialization/hotspot.js';
export { LectureSession } from './nua-serialization/lecture-session.js';
export { OptionSelection } from './nua-serialization/option-selection.js';
export { Quiz } from './nua-serialization/quiz.js';
export { TelemetryPayload } from './nua-serialization/telemetry-payload.js';
export { TimeSegment } from './nua-serialization/time-segment.js';
