// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Hotspot {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Hotspot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHotspot(bb:flatbuffers.ByteBuffer, obj?:Hotspot):Hotspot {
  return (obj || new Hotspot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHotspot(bb:flatbuffers.ByteBuffer, obj?:Hotspot):Hotspot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Hotspot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

token():string|null
token(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
token(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

conceptDefinition():string|null
conceptDefinition(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
conceptDefinition(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startHotspot(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addToken(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, tokenOffset, 0);
}

static addConceptDefinition(builder:flatbuffers.Builder, conceptDefinitionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, conceptDefinitionOffset, 0);
}

static endHotspot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHotspot(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset, conceptDefinitionOffset:flatbuffers.Offset):flatbuffers.Offset {
  Hotspot.startHotspot(builder);
  Hotspot.addToken(builder, tokenOffset);
  Hotspot.addConceptDefinition(builder, conceptDefinitionOffset);
  return Hotspot.endHotspot(builder);
}
}
