// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GraphNode } from '../nua-serialization/graph-node.js';
import { Quiz } from '../nua-serialization/quiz.js';
import { TelemetryPayload } from '../nua-serialization/telemetry-payload.js';
import { TimeSegment } from '../nua-serialization/time-segment.js';


export class LectureSession {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LectureSession {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLectureSession(bb:flatbuffers.ByteBuffer, obj?:LectureSession):LectureSession {
  return (obj || new LectureSession()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLectureSession(bb:flatbuffers.ByteBuffer, obj?:LectureSession):LectureSession {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LectureSession()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

schemaVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 1;
}

sessionId():string|null
sessionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sessionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sourceLang():string|null
sourceLang(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sourceLang(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

targetLang():string|null
targetLang(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
targetLang(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sourceVideoPath():string|null
sourceVideoPath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sourceVideoPath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

timelineTracks(index: number, obj?:TimeSegment):TimeSegment|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new TimeSegment()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

timelineTracksLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

quizzes(index: number, obj?:Quiz):Quiz|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new Quiz()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

quizzesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

knowledgeGraph(index: number, obj?:GraphNode):GraphNode|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new GraphNode()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

knowledgeGraphLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

telemetryLedger(index: number, obj?:TelemetryPayload):TelemetryPayload|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new TelemetryPayload()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

telemetryLedgerLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startLectureSession(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addSchemaVersion(builder:flatbuffers.Builder, schemaVersion:number) {
  builder.addFieldInt16(0, schemaVersion, 1);
}

static addSessionId(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sessionIdOffset, 0);
}

static addSourceLang(builder:flatbuffers.Builder, sourceLangOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sourceLangOffset, 0);
}

static addTargetLang(builder:flatbuffers.Builder, targetLangOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, targetLangOffset, 0);
}

static addSourceVideoPath(builder:flatbuffers.Builder, sourceVideoPathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, sourceVideoPathOffset, 0);
}

static addTimelineTracks(builder:flatbuffers.Builder, timelineTracksOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, timelineTracksOffset, 0);
}

static createTimelineTracksVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTimelineTracksVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addQuizzes(builder:flatbuffers.Builder, quizzesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, quizzesOffset, 0);
}

static createQuizzesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startQuizzesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addKnowledgeGraph(builder:flatbuffers.Builder, knowledgeGraphOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, knowledgeGraphOffset, 0);
}

static createKnowledgeGraphVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startKnowledgeGraphVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTelemetryLedger(builder:flatbuffers.Builder, telemetryLedgerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, telemetryLedgerOffset, 0);
}

static createTelemetryLedgerVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTelemetryLedgerVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endLectureSession(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLectureSession(builder:flatbuffers.Builder, schemaVersion:number, sessionIdOffset:flatbuffers.Offset, sourceLangOffset:flatbuffers.Offset, targetLangOffset:flatbuffers.Offset, sourceVideoPathOffset:flatbuffers.Offset, timelineTracksOffset:flatbuffers.Offset, quizzesOffset:flatbuffers.Offset, knowledgeGraphOffset:flatbuffers.Offset, telemetryLedgerOffset:flatbuffers.Offset):flatbuffers.Offset {
  LectureSession.startLectureSession(builder);
  LectureSession.addSchemaVersion(builder, schemaVersion);
  LectureSession.addSessionId(builder, sessionIdOffset);
  LectureSession.addSourceLang(builder, sourceLangOffset);
  LectureSession.addTargetLang(builder, targetLangOffset);
  LectureSession.addSourceVideoPath(builder, sourceVideoPathOffset);
  LectureSession.addTimelineTracks(builder, timelineTracksOffset);
  LectureSession.addQuizzes(builder, quizzesOffset);
  LectureSession.addKnowledgeGraph(builder, knowledgeGraphOffset);
  LectureSession.addTelemetryLedger(builder, telemetryLedgerOffset);
  return LectureSession.endLectureSession(builder);
}
}
