// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class OptionSelection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OptionSelection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOptionSelection(bb:flatbuffers.ByteBuffer, obj?:OptionSelection):OptionSelection {
  return (obj || new OptionSelection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOptionSelection(bb:flatbuffers.ByteBuffer, obj?:OptionSelection):OptionSelection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OptionSelection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

quizId():string|null
quizId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
quizId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

selectedIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

latencyMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

isCorrect():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startOptionSelection(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addQuizId(builder:flatbuffers.Builder, quizIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, quizIdOffset, 0);
}

static addSelectedIndex(builder:flatbuffers.Builder, selectedIndex:number) {
  builder.addFieldInt8(1, selectedIndex, 0);
}

static addLatencyMs(builder:flatbuffers.Builder, latencyMs:number) {
  builder.addFieldInt32(2, latencyMs, 0);
}

static addIsCorrect(builder:flatbuffers.Builder, isCorrect:boolean) {
  builder.addFieldInt8(3, +isCorrect, +false);
}

static endOptionSelection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOptionSelection(builder:flatbuffers.Builder, quizIdOffset:flatbuffers.Offset, selectedIndex:number, latencyMs:number, isCorrect:boolean):flatbuffers.Offset {
  OptionSelection.startOptionSelection(builder);
  OptionSelection.addQuizId(builder, quizIdOffset);
  OptionSelection.addSelectedIndex(builder, selectedIndex);
  OptionSelection.addLatencyMs(builder, latencyMs);
  OptionSelection.addIsCorrect(builder, isCorrect);
  return OptionSelection.endOptionSelection(builder);
}
}
