// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Quiz {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Quiz {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQuiz(bb:flatbuffers.ByteBuffer, obj?:Quiz):Quiz {
  return (obj || new Quiz()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQuiz(bb:flatbuffers.ByteBuffer, obj?:Quiz):Quiz {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Quiz()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

triggerTimestampMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

question():string|null
question(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
question(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

options(index: number):string
options(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
options(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

optionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

correctIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startQuiz(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addTriggerTimestampMs(builder:flatbuffers.Builder, triggerTimestampMs:bigint) {
  builder.addFieldInt64(0, triggerTimestampMs, BigInt('0'));
}

static addQuestion(builder:flatbuffers.Builder, questionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, questionOffset, 0);
}

static addOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, optionsOffset, 0);
}

static createOptionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startOptionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCorrectIndex(builder:flatbuffers.Builder, correctIndex:number) {
  builder.addFieldInt8(3, correctIndex, 0);
}

static endQuiz(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQuiz(builder:flatbuffers.Builder, triggerTimestampMs:bigint, questionOffset:flatbuffers.Offset, optionsOffset:flatbuffers.Offset, correctIndex:number):flatbuffers.Offset {
  Quiz.startQuiz(builder);
  Quiz.addTriggerTimestampMs(builder, triggerTimestampMs);
  Quiz.addQuestion(builder, questionOffset);
  Quiz.addOptions(builder, optionsOffset);
  Quiz.addCorrectIndex(builder, correctIndex);
  return Quiz.endQuiz(builder);
}
}
