// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { OptionSelection } from '../nua-serialization/option-selection.js';


export class TelemetryPayload {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TelemetryPayload {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTelemetryPayload(bb:flatbuffers.ByteBuffer, obj?:TelemetryPayload):TelemetryPayload {
  return (obj || new TelemetryPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTelemetryPayload(bb:flatbuffers.ByteBuffer, obj?:TelemetryPayload):TelemetryPayload {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TelemetryPayload()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sessionId():string|null
sessionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sessionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

completionPercentage():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

quizResponses(index: number, obj?:OptionSelection):OptionSelection|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new OptionSelection()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

quizResponsesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

cryptographicSignature():string|null
cryptographicSignature(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cryptographicSignature(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTelemetryPayload(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addSessionId(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sessionIdOffset, 0);
}

static addCompletionPercentage(builder:flatbuffers.Builder, completionPercentage:number) {
  builder.addFieldInt8(1, completionPercentage, 0);
}

static addQuizResponses(builder:flatbuffers.Builder, quizResponsesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, quizResponsesOffset, 0);
}

static createQuizResponsesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startQuizResponsesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCryptographicSignature(builder:flatbuffers.Builder, cryptographicSignatureOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, cryptographicSignatureOffset, 0);
}

static endTelemetryPayload(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTelemetryPayload(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset, completionPercentage:number, quizResponsesOffset:flatbuffers.Offset, cryptographicSignatureOffset:flatbuffers.Offset):flatbuffers.Offset {
  TelemetryPayload.startTelemetryPayload(builder);
  TelemetryPayload.addSessionId(builder, sessionIdOffset);
  TelemetryPayload.addCompletionPercentage(builder, completionPercentage);
  TelemetryPayload.addQuizResponses(builder, quizResponsesOffset);
  TelemetryPayload.addCryptographicSignature(builder, cryptographicSignatureOffset);
  return TelemetryPayload.endTelemetryPayload(builder);
}
}
