// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Hotspot } from '../nua-serialization/hotspot.js';


export class TimeSegment {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TimeSegment {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTimeSegment(bb:flatbuffers.ByteBuffer, obj?:TimeSegment):TimeSegment {
  return (obj || new TimeSegment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTimeSegment(bb:flatbuffers.ByteBuffer, obj?:TimeSegment):TimeSegment {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TimeSegment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

segmentId():string|null
segmentId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
segmentId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

videoStartMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

videoEndMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

audioSourcePath():string|null
audioSourcePath(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
audioSourcePath(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

audioDurationMs():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

originalText():string|null
originalText(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
originalText(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

translatedText():string|null
translatedText(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
translatedText(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

shouldFreeze():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hotspots(index: number, obj?:Hotspot):Hotspot|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new Hotspot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

hotspotsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

directive():string|null
directive(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
directive(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startTimeSegment(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addSegmentId(builder:flatbuffers.Builder, segmentIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, segmentIdOffset, 0);
}

static addVideoStartMs(builder:flatbuffers.Builder, videoStartMs:number) {
  builder.addFieldInt32(1, videoStartMs, 0);
}

static addVideoEndMs(builder:flatbuffers.Builder, videoEndMs:number) {
  builder.addFieldInt32(2, videoEndMs, 0);
}

static addAudioSourcePath(builder:flatbuffers.Builder, audioSourcePathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, audioSourcePathOffset, 0);
}

static addAudioDurationMs(builder:flatbuffers.Builder, audioDurationMs:number) {
  builder.addFieldInt32(4, audioDurationMs, 0);
}

static addOriginalText(builder:flatbuffers.Builder, originalTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, originalTextOffset, 0);
}

static addTranslatedText(builder:flatbuffers.Builder, translatedTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, translatedTextOffset, 0);
}

static addShouldFreeze(builder:flatbuffers.Builder, shouldFreeze:boolean) {
  builder.addFieldInt8(7, +shouldFreeze, +false);
}

static addHotspots(builder:flatbuffers.Builder, hotspotsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, hotspotsOffset, 0);
}

static createHotspotsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHotspotsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDirective(builder:flatbuffers.Builder, directiveOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, directiveOffset, 0);
}

static endTimeSegment(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTimeSegment(builder:flatbuffers.Builder, segmentIdOffset:flatbuffers.Offset, videoStartMs:number, videoEndMs:number, audioSourcePathOffset:flatbuffers.Offset, audioDurationMs:number, originalTextOffset:flatbuffers.Offset, translatedTextOffset:flatbuffers.Offset, shouldFreeze:boolean, hotspotsOffset:flatbuffers.Offset, directiveOffset:flatbuffers.Offset):flatbuffers.Offset {
  TimeSegment.startTimeSegment(builder);
  TimeSegment.addSegmentId(builder, segmentIdOffset);
  TimeSegment.addVideoStartMs(builder, videoStartMs);
  TimeSegment.addVideoEndMs(builder, videoEndMs);
  TimeSegment.addAudioSourcePath(builder, audioSourcePathOffset);
  TimeSegment.addAudioDurationMs(builder, audioDurationMs);
  TimeSegment.addOriginalText(builder, originalTextOffset);
  TimeSegment.addTranslatedText(builder, translatedTextOffset);
  TimeSegment.addShouldFreeze(builder, shouldFreeze);
  TimeSegment.addHotspots(builder, hotspotsOffset);
  TimeSegment.addDirective(builder, directiveOffset);
  return TimeSegment.endTimeSegment(builder);
}
}
