// automatically generated by the FlatBuffers compiler, do not modify

package org.nua.production.app.data.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TelemetryRecord : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TelemetryRecord {
        __init(_i, _bb)
        return this
    }
    val sessionId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sessionIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun sessionIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val completionPercentage : Int
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val sequenceVersion : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val timestamp : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTelemetryRecord(_bb: ByteBuffer): TelemetryRecord = getRootAsTelemetryRecord(_bb, TelemetryRecord())
        fun getRootAsTelemetryRecord(_bb: ByteBuffer, obj: TelemetryRecord): TelemetryRecord {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun TelemetryRecordBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NUAB")
        fun createTelemetryRecord(builder: FlatBufferBuilder, sessionIdOffset: Int, completionPercentage: Int, sequenceVersion: ULong, timestamp: ULong) : Int {
            builder.startTable(4)
            addTimestamp(builder, timestamp)
            addSequenceVersion(builder, sequenceVersion)
            addCompletionPercentage(builder, completionPercentage)
            addSessionId(builder, sessionIdOffset)
            return endTelemetryRecord(builder)
        }
        fun startTelemetryRecord(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addSessionId(builder: FlatBufferBuilder, sessionId: Int) = builder.addOffset(0, sessionId, 0)
        fun addCompletionPercentage(builder: FlatBufferBuilder, completionPercentage: Int) = builder.addInt(1, completionPercentage, 0)
        fun addSequenceVersion(builder: FlatBufferBuilder, sequenceVersion: ULong) = builder.addLong(2, sequenceVersion.toLong(), 0)
        fun addTimestamp(builder: FlatBufferBuilder, timestamp: ULong) = builder.addLong(3, timestamp.toLong(), 0)
        fun endTelemetryRecord(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishTelemetryRecordBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NUAB")
        fun finishSizePrefixedTelemetryRecordBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NUAB")
    }
}
