// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class GraphNode : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : GraphNode {
        __init(_i, _bb)
        return this
    }
    val nodeId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nodeIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun nodeIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    fun keywords(j: Int) : String? {
        val o = __offset(6)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val keywordsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val summaryFactoid : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val summaryFactoidAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun summaryFactoidInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    fun contextTokens(j: Int) : String? {
        val o = __offset(10)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val contextTokensLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsGraphNode(_bb: ByteBuffer): GraphNode = getRootAsGraphNode(_bb, GraphNode())
        fun getRootAsGraphNode(_bb: ByteBuffer, obj: GraphNode): GraphNode {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createGraphNode(builder: FlatBufferBuilder, nodeIdOffset: Int, keywordsOffset: Int, summaryFactoidOffset: Int, contextTokensOffset: Int) : Int {
            builder.startTable(4)
            addContextTokens(builder, contextTokensOffset)
            addSummaryFactoid(builder, summaryFactoidOffset)
            addKeywords(builder, keywordsOffset)
            addNodeId(builder, nodeIdOffset)
            return endGraphNode(builder)
        }
        fun startGraphNode(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addNodeId(builder: FlatBufferBuilder, nodeId: Int) = builder.addOffset(0, nodeId, 0)
        fun addKeywords(builder: FlatBufferBuilder, keywords: Int) = builder.addOffset(1, keywords, 0)
        fun createKeywordsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startKeywordsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addSummaryFactoid(builder: FlatBufferBuilder, summaryFactoid: Int) = builder.addOffset(2, summaryFactoid, 0)
        fun addContextTokens(builder: FlatBufferBuilder, contextTokens: Int) = builder.addOffset(3, contextTokens, 0)
        fun createContextTokensVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startContextTokensVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endGraphNode(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
