// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Hotspot : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Hotspot {
        __init(_i, _bb)
        return this
    }
    val token : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val tokenAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun tokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val conceptDefinition : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val conceptDefinitionAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun conceptDefinitionInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsHotspot(_bb: ByteBuffer): Hotspot = getRootAsHotspot(_bb, Hotspot())
        fun getRootAsHotspot(_bb: ByteBuffer, obj: Hotspot): Hotspot {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createHotspot(builder: FlatBufferBuilder, tokenOffset: Int, conceptDefinitionOffset: Int) : Int {
            builder.startTable(2)
            addConceptDefinition(builder, conceptDefinitionOffset)
            addToken(builder, tokenOffset)
            return endHotspot(builder)
        }
        fun startHotspot(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addToken(builder: FlatBufferBuilder, token: Int) = builder.addOffset(0, token, 0)
        fun addConceptDefinition(builder: FlatBufferBuilder, conceptDefinition: Int) = builder.addOffset(1, conceptDefinition, 0)
        fun endHotspot(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
