// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class LectureSession : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LectureSession {
        __init(_i, _bb)
        return this
    }
    val schemaVersion : UShort
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 1u
        }
    val sessionId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sessionIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun sessionIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val sourceLang : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceLangAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun sourceLangInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    val targetLang : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val targetLangAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun targetLangInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val sourceVideoPath : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceVideoPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun sourceVideoPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    fun timelineTracks(j: Int) : NuaSerialization.TimeSegment? = timelineTracks(NuaSerialization.TimeSegment(), j)
    fun timelineTracks(obj: NuaSerialization.TimeSegment, j: Int) : NuaSerialization.TimeSegment? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val timelineTracksLength : Int
        get() {
            val o = __offset(16); return if (o != 0) __vector_len(o) else 0
        }
    fun quizzes(j: Int) : NuaSerialization.Quiz? = quizzes(NuaSerialization.Quiz(), j)
    fun quizzes(obj: NuaSerialization.Quiz, j: Int) : NuaSerialization.Quiz? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val quizzesLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    fun knowledgeGraph(j: Int) : NuaSerialization.GraphNode? = knowledgeGraph(NuaSerialization.GraphNode(), j)
    fun knowledgeGraph(obj: NuaSerialization.GraphNode, j: Int) : NuaSerialization.GraphNode? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val knowledgeGraphLength : Int
        get() {
            val o = __offset(20); return if (o != 0) __vector_len(o) else 0
        }
    fun telemetryLedger(j: Int) : NuaSerialization.TelemetryPayload? = telemetryLedger(NuaSerialization.TelemetryPayload(), j)
    fun telemetryLedger(obj: NuaSerialization.TelemetryPayload, j: Int) : NuaSerialization.TelemetryPayload? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val telemetryLedgerLength : Int
        get() {
            val o = __offset(22); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsLectureSession(_bb: ByteBuffer): LectureSession = getRootAsLectureSession(_bb, LectureSession())
        fun getRootAsLectureSession(_bb: ByteBuffer, obj: LectureSession): LectureSession {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun LectureSessionBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NUAB")
        fun createLectureSession(builder: FlatBufferBuilder, schemaVersion: UShort, sessionIdOffset: Int, sourceLangOffset: Int, targetLangOffset: Int, sourceVideoPathOffset: Int, timelineTracksOffset: Int, quizzesOffset: Int, knowledgeGraphOffset: Int, telemetryLedgerOffset: Int) : Int {
            builder.startTable(10)
            addTelemetryLedger(builder, telemetryLedgerOffset)
            addKnowledgeGraph(builder, knowledgeGraphOffset)
            addQuizzes(builder, quizzesOffset)
            addTimelineTracks(builder, timelineTracksOffset)
            addSourceVideoPath(builder, sourceVideoPathOffset)
            addTargetLang(builder, targetLangOffset)
            addSourceLang(builder, sourceLangOffset)
            addSessionId(builder, sessionIdOffset)
            addSchemaVersion(builder, schemaVersion)
            return endLectureSession(builder)
        }
        fun startLectureSession(builder: FlatBufferBuilder) = builder.startTable(10)
        fun addSchemaVersion(builder: FlatBufferBuilder, schemaVersion: UShort) = builder.addShort(0, schemaVersion.toShort(), 1)
        fun addSessionId(builder: FlatBufferBuilder, sessionId: Int) = builder.addOffset(1, sessionId, 0)
        fun addSourceLang(builder: FlatBufferBuilder, sourceLang: Int) = builder.addOffset(2, sourceLang, 0)
        fun addTargetLang(builder: FlatBufferBuilder, targetLang: Int) = builder.addOffset(3, targetLang, 0)
        fun addSourceVideoPath(builder: FlatBufferBuilder, sourceVideoPath: Int) = builder.addOffset(5, sourceVideoPath, 0)
        fun addTimelineTracks(builder: FlatBufferBuilder, timelineTracks: Int) = builder.addOffset(6, timelineTracks, 0)
        fun createTimelineTracksVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startTimelineTracksVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addQuizzes(builder: FlatBufferBuilder, quizzes: Int) = builder.addOffset(7, quizzes, 0)
        fun createQuizzesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startQuizzesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addKnowledgeGraph(builder: FlatBufferBuilder, knowledgeGraph: Int) = builder.addOffset(8, knowledgeGraph, 0)
        fun createKnowledgeGraphVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startKnowledgeGraphVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addTelemetryLedger(builder: FlatBufferBuilder, telemetryLedger: Int) = builder.addOffset(9, telemetryLedger, 0)
        fun createTelemetryLedgerVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startTelemetryLedgerVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endLectureSession(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishLectureSessionBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NUAB")
        fun finishSizePrefixedLectureSessionBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NUAB")
    }
}
