// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class OptionSelection : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : OptionSelection {
        __init(_i, _bb)
        return this
    }
    val quizId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val quizIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun quizIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val selectedOptionIndex : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val latencyMs : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val isCorrect : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsOptionSelection(_bb: ByteBuffer): OptionSelection = getRootAsOptionSelection(_bb, OptionSelection())
        fun getRootAsOptionSelection(_bb: ByteBuffer, obj: OptionSelection): OptionSelection {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createOptionSelection(builder: FlatBufferBuilder, quizIdOffset: Int, selectedOptionIndex: UByte, latencyMs: UInt, isCorrect: Boolean) : Int {
            builder.startTable(4)
            addLatencyMs(builder, latencyMs)
            addQuizId(builder, quizIdOffset)
            addIsCorrect(builder, isCorrect)
            addSelectedOptionIndex(builder, selectedOptionIndex)
            return endOptionSelection(builder)
        }
        fun startOptionSelection(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addQuizId(builder: FlatBufferBuilder, quizId: Int) = builder.addOffset(0, quizId, 0)
        fun addSelectedOptionIndex(builder: FlatBufferBuilder, selectedOptionIndex: UByte) = builder.addByte(1, selectedOptionIndex.toByte(), 0)
        fun addLatencyMs(builder: FlatBufferBuilder, latencyMs: UInt) = builder.addInt(2, latencyMs.toInt(), 0)
        fun addIsCorrect(builder: FlatBufferBuilder, isCorrect: Boolean) = builder.addBoolean(3, isCorrect, false)
        fun endOptionSelection(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
