// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Quiz : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Quiz {
        __init(_i, _bb)
        return this
    }
    val triggerTimestampMs : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val question : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val questionAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun questionInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    fun options(j: Int) : String? {
        val o = __offset(8)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val optionsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val correctIndex : UByte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsQuiz(_bb: ByteBuffer): Quiz = getRootAsQuiz(_bb, Quiz())
        fun getRootAsQuiz(_bb: ByteBuffer, obj: Quiz): Quiz {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createQuiz(builder: FlatBufferBuilder, triggerTimestampMs: UInt, questionOffset: Int, optionsOffset: Int, correctIndex: UByte) : Int {
            builder.startTable(4)
            addOptions(builder, optionsOffset)
            addQuestion(builder, questionOffset)
            addTriggerTimestampMs(builder, triggerTimestampMs)
            addCorrectIndex(builder, correctIndex)
            return endQuiz(builder)
        }
        fun startQuiz(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addTriggerTimestampMs(builder: FlatBufferBuilder, triggerTimestampMs: UInt) = builder.addInt(0, triggerTimestampMs.toInt(), 0)
        fun addQuestion(builder: FlatBufferBuilder, question: Int) = builder.addOffset(1, question, 0)
        fun addOptions(builder: FlatBufferBuilder, options: Int) = builder.addOffset(2, options, 0)
        fun createOptionsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startOptionsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addCorrectIndex(builder: FlatBufferBuilder, correctIndex: UByte) = builder.addByte(3, correctIndex.toByte(), 0)
        fun endQuiz(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
