// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TelemetryPayload : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TelemetryPayload {
        __init(_i, _bb)
        return this
    }
    val sessionId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sessionIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun sessionIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val completionPercentage : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun quizResponses(j: Int) : NuaSerialization.OptionSelection? = quizResponses(NuaSerialization.OptionSelection(), j)
    fun quizResponses(obj: NuaSerialization.OptionSelection, j: Int) : NuaSerialization.OptionSelection? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val quizResponsesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val cryptographicSignature : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val cryptographicSignatureAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun cryptographicSignatureInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTelemetryPayload(_bb: ByteBuffer): TelemetryPayload = getRootAsTelemetryPayload(_bb, TelemetryPayload())
        fun getRootAsTelemetryPayload(_bb: ByteBuffer, obj: TelemetryPayload): TelemetryPayload {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTelemetryPayload(builder: FlatBufferBuilder, sessionIdOffset: Int, completionPercentage: UByte, quizResponsesOffset: Int, cryptographicSignatureOffset: Int) : Int {
            builder.startTable(4)
            addCryptographicSignature(builder, cryptographicSignatureOffset)
            addQuizResponses(builder, quizResponsesOffset)
            addSessionId(builder, sessionIdOffset)
            addCompletionPercentage(builder, completionPercentage)
            return endTelemetryPayload(builder)
        }
        fun startTelemetryPayload(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addSessionId(builder: FlatBufferBuilder, sessionId: Int) = builder.addOffset(0, sessionId, 0)
        fun addCompletionPercentage(builder: FlatBufferBuilder, completionPercentage: UByte) = builder.addByte(1, completionPercentage.toByte(), 0)
        fun addQuizResponses(builder: FlatBufferBuilder, quizResponses: Int) = builder.addOffset(2, quizResponses, 0)
        fun createQuizResponsesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startQuizResponsesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addCryptographicSignature(builder: FlatBufferBuilder, cryptographicSignature: Int) = builder.addOffset(3, cryptographicSignature, 0)
        fun endTelemetryPayload(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
