// automatically generated by the FlatBuffers compiler, do not modify

package NuaSerialization

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TimeSegment : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TimeSegment {
        __init(_i, _bb)
        return this
    }
    val segmentId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val segmentIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(4, 1)
    fun segmentIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 4, 1)
    val videoStartMs : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val videoEndMs : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val audioSourcePath : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val audioSourcePathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun audioSourcePathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val audioDurationMs : UInt
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val originalText : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val originalTextAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun originalTextInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val translatedText : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val translatedTextAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(16, 1)
    fun translatedTextInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 16, 1)
    val directive : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val directiveAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(18, 1)
    fun directiveInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 18, 1)
    fun hotspots(j: Int) : NuaSerialization.Hotspot? = hotspots(NuaSerialization.Hotspot(), j)
    fun hotspots(obj: NuaSerialization.Hotspot, j: Int) : NuaSerialization.Hotspot? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val hotspotsLength : Int
        get() {
            val o = __offset(20); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTimeSegment(_bb: ByteBuffer): TimeSegment = getRootAsTimeSegment(_bb, TimeSegment())
        fun getRootAsTimeSegment(_bb: ByteBuffer, obj: TimeSegment): TimeSegment {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTimeSegment(builder: FlatBufferBuilder, segmentIdOffset: Int, videoStartMs: UInt, videoEndMs: UInt, audioSourcePathOffset: Int, audioDurationMs: UInt, originalTextOffset: Int, translatedTextOffset: Int, directiveOffset: Int, hotspotsOffset: Int) : Int {
            builder.startTable(9)
            addHotspots(builder, hotspotsOffset)
            addDirective(builder, directiveOffset)
            addTranslatedText(builder, translatedTextOffset)
            addOriginalText(builder, originalTextOffset)
            addAudioDurationMs(builder, audioDurationMs)
            addAudioSourcePath(builder, audioSourcePathOffset)
            addVideoEndMs(builder, videoEndMs)
            addVideoStartMs(builder, videoStartMs)
            addSegmentId(builder, segmentIdOffset)
            return endTimeSegment(builder)
        }
        fun startTimeSegment(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addSegmentId(builder: FlatBufferBuilder, segmentId: Int) = builder.addOffset(0, segmentId, 0)
        fun addVideoStartMs(builder: FlatBufferBuilder, videoStartMs: UInt) = builder.addInt(1, videoStartMs.toInt(), 0)
        fun addVideoEndMs(builder: FlatBufferBuilder, videoEndMs: UInt) = builder.addInt(2, videoEndMs.toInt(), 0)
        fun addAudioSourcePath(builder: FlatBufferBuilder, audioSourcePath: Int) = builder.addOffset(3, audioSourcePath, 0)
        fun addAudioDurationMs(builder: FlatBufferBuilder, audioDurationMs: UInt) = builder.addInt(4, audioDurationMs.toInt(), 0)
        fun addOriginalText(builder: FlatBufferBuilder, originalText: Int) = builder.addOffset(5, originalText, 0)
        fun addTranslatedText(builder: FlatBufferBuilder, translatedText: Int) = builder.addOffset(6, translatedText, 0)
        fun addDirective(builder: FlatBufferBuilder, directive: Int) = builder.addOffset(7, directive, 0)
        fun addHotspots(builder: FlatBufferBuilder, hotspots: Int) = builder.addOffset(8, hotspots, 0)
        fun createHotspotsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startHotspotsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endTimeSegment(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
