// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class TelemetryRecord {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TelemetryRecord {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTelemetryRecord(bb:flatbuffers.ByteBuffer, obj?:TelemetryRecord):TelemetryRecord {
  return (obj || new TelemetryRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTelemetryRecord(bb:flatbuffers.ByteBuffer, obj?:TelemetryRecord):TelemetryRecord {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TelemetryRecord()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static bufferHasIdentifier(bb:flatbuffers.ByteBuffer):boolean {
  return bb.__has_identifier('NUAB');
}

sessionId():string|null
sessionId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sessionId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

completionPercentage():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

sequenceVersion():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

timestamp():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startTelemetryRecord(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addSessionId(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, sessionIdOffset, 0);
}

static addCompletionPercentage(builder:flatbuffers.Builder, completionPercentage:number) {
  builder.addFieldInt32(1, completionPercentage, 0);
}

static addSequenceVersion(builder:flatbuffers.Builder, sequenceVersion:bigint) {
  builder.addFieldInt64(2, sequenceVersion, BigInt('0'));
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:bigint) {
  builder.addFieldInt64(3, timestamp, BigInt('0'));
}

static endTelemetryRecord(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishTelemetryRecordBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'NUAB');
}

static finishSizePrefixedTelemetryRecordBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, 'NUAB', true);
}

static createTelemetryRecord(builder:flatbuffers.Builder, sessionIdOffset:flatbuffers.Offset, completionPercentage:number, sequenceVersion:bigint, timestamp:bigint):flatbuffers.Offset {
  TelemetryRecord.startTelemetryRecord(builder);
  TelemetryRecord.addSessionId(builder, sessionIdOffset);
  TelemetryRecord.addCompletionPercentage(builder, completionPercentage);
  TelemetryRecord.addSequenceVersion(builder, sequenceVersion);
  TelemetryRecord.addTimestamp(builder, timestamp);
  return TelemetryRecord.endTelemetryRecord(builder);
}
}
